version: '3.8'

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v2.9.5}
    command:
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.network=webmmx
      - --providers.docker.exposedByDefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    networks:
      - webmmx
    volumes:
      - ${VOLUME_PATH}letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - {target: 80, published: 80, mode: host, protocol: tcp}
      - {target: 443, published: 443, mode: host, protocol: tcp}
  webmmx:
    image: webmmx:latest
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.webmmx.rule=Host(`${DOMAIN:-webmmx.traefik.me}`)
      - traefik.http.routers.webmmx.entrypoints=${SCHEME:-https}
      - traefik.http.routers.webmmx.service=webmmx
      - traefik.http.routers.webmmx.tls.certresolver=letsencrypt
      - traefik.http.services.webmmx.loadbalancer.server.port=80
    networks:
      - webmmx
volumes:
  letsencrypt:
networks:
  webmmx: